### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by donavanbecker** [EricAndrechek/homebridge-display#1]
Any way you could publish this to npm?

**Comment by EricAndrechek** [comment]
I plan on adding that functionality ASAP, I'm trying to take all the input I've received and then make this a Homebridge plugin, but I don't have much experience in npm and node so it will be a fun journey!

**Comment by donavanbecker** [comment]
Check out homebridge-Honeywell-home. GitHub has nice Actions that making publishing to npm easier.

**Comment by EricAndrechek** [comment]
I've got the npm and Homebridge plugin side of things working, now it's just a matter of converting everything from python to JavaScript.

**Comment by EricAndrechek** [comment]
The first release of public beta has been released and is [on NPM](https://www.npmjs.com/package/homebridge-display)! It currently has limited functionality but it's a start!
