### ISSUE TITLE
Openweather

### ISSUE THREAD

**Issue by atSeptine** [EricAndrechek/homebridge-display#108]
Hello EricAndrechek, I like this plugin.!
you can Openweather program it to the temperature in celsius and the language in German…thanks!

**Comment by jan-luebbers** [comment]
Also would love some Celsius.
Thanks for the plugin!

**Comment by EricAndrechek** [comment]
Thanks for the input! I have a release I am currently working on and hope to have it rolled out after some more testing late this week, which will include Celsius.

**Comment by atSeptine** [comment]
👍

**Comment by EricAndrechek** [comment]
Done! [Version 2.1.0](https://github.com/EricAndrechek/homebridge-display/releases/tag/2.1.0) has been released and now supports metric or imperial in the weather config.

**Comment by atSeptine** [comment]
Thanks for update....👌
