### ISSUE TITLE
Accessory widget box empty, weather no data

### ISSUE THREAD

**Issue by MAPEZ1** [EricAndrechek/homebridge-display#113]
Hello Eric, thanx a lot for creating the plugin.
I really like to try it as I would like to provide to my family a less developer focused dashboard.
Just as easy & clean as yours look like.... 👍🏼
But I'm running into issues and have also a question.

I have Homebridge 1.2.5 running on Raspi4, node v12.18.4 and Homebridge-Display 2.1.0
It loads and registers without errors.

Homebridge is starting as service on raspi:
homebridge.service contains: ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS
and the homebridge script contains: HOMEBRIDGE_OPTS=-I -U /var/homebridge
So I believe Homebridge is starting with -I parameter as I have the Accessory widget
via homebridge-config-ui-x v4.36.0 also working.

I have defined the 6 Boxes - 4 for Accessory Control, 1 for Calculator and the 6th for Weather.
The API for Openweather I have already working with the Weather Plus plugin.
But the Weather Widget shows only XX° (config to Celsius)
The Calculator is shown, but not clickable in browser FF, Safari on MAC catalina 10.15.7 or on iPad mini 4 iOS 14.3
Nothing is shown in the 4 Accessory Control Boxes

Despite the issue I have the question how the accessories would be split between the Boxes,
or if all boxes would show the same ? Then  a configuration for those Accessory Boxes would be great.

Hope I could explain enough the issue. 

![FBBC4207-85F1-4211-BDD8-54FD16BCE48C](https://user-images.githubusercontent.com/76261897/107127424-4ff93200-68b6-11eb-8cce-81aa815db0c7.png)

**Comment by EricAndrechek** [comment]
Hi, I appreciate the kind words about the plugin. Currently, you can only have one accessory widget displayed at a time, but that is my top priority right now as I have heard from many people that they would like to add more. I don't know exactly why your browser wouldn't be showing anything, could you run homebridge in debug mode and then let me know if anything is outputted there? Also, if you open the homebridge-display web interface on your computer and then right-click to view the inspect element/developer tools, there should be a console on there where you can see what its issues are too. If you can get back to me with the debug messages in those two places, I am confident we can get this working.

**Comment by MAPEZ1** [comment]
Hi Eric, found it. Reason was that I had in more than one Box IOT. As soon as I configured only one and Blank in all others, Homebridge-Display showed some Random Delay Switches but without an icon.
![image](https://user-images.githubusercontent.com/76261897/107284499-3692ea00-6a5e-11eb-8ad3-385df8845dc8.png)

The error which occured was:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/76261897/107284372-00556a80-6a5e-11eb-89b5-468fea9d76e0.png">

The black line did not always show up. It might be that it is related to the Weather Box which does not show the right values.
![image](https://user-images.githubusercontent.com/76261897/107287656-896ea080-6a62-11eb-9956-a84c8b157b71.png)
We have currently -9° C (14.7° F) and it will get even colder.

When I clicked further, it showed this:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/76261897/107285892-17955780-6a60-11eb-9756-d5b30cea532c.png">

Thanx again and please let me know if I can help more with testing and feedback.

**Comment by EricAndrechek** [comment]
Glad to hear you got the IOT widget working, with how it works right now, only the first 6 devices it discovers are displayed, and it tries its best to guess the appropriate icon. I hope to roll out an update to allow you to specify which devices to show in what order, and to allow you to add multiple accessory widgets sometime soon, I'm aiming for the end of next week, but I don't know how many issues I'll run into. 

Regarding weather, the only thing I can imagine that would be causing it to be off is if something isn't quite right in your config for the latitude and longitude. If you open ["https://api.openweathermap.org/data/2.5/onecall?lat=YOUR_LAT_HERE&lon=YOUR_LON_HERE&units=metric&appid=YOUR_API_KEY_HERE"](https://api.openweathermap.org/data/2.5/onecall?lat=YOUR_LAT_HERE&lon=YOUR_LON_HERE&units=metric&appid=YOUR_API_KEY_HERE) in your browser in a new tab (replacing the necessary things with the fields in your config) see if that matches what you are getting from homebridge-display. I know occasionally OpenWeatherMap can report slightly different temperatures than my phone (ie right now my phone is reporting 14F and my homebridge-display is reporting 16F) but it shouldn't be as extreme as yours is.

**Comment by MAPEZ1** [comment]
Hi Eric,
excellent...thanx for the link. You where right .. Coordinates where mixed up.
Closing this. Thanks a lot.
