### ISSUE TITLE
Clock Widget

### ISSUE THREAD

**Issue by WummoFTW** [EricAndrechek/homebridge-display#119]
Imagine a ✨Clock Widget✨

Nothing fancy, just a widget that shows time, no timers, no timelines, just time.

**Comment by EricAndrechek** [comment]
I don't know why I never thought to add this... It will be in the next release of homebridge-display, thanks for the input!

**Comment by EricAndrechek** [comment]
Alright, the clock widget has been deployed and is now in the latest release. Thanks for your input! Widget completed and issue closed. Refer to [the clock section in the wiki](https://github.com/EricAndrechek/homebridge-display/wiki/clock) for info on how to set up the clock widget, and if you have further requests or questions feel free to comment them here, or create a new issue.
