### ISSUE TITLE
Accessory Control

### ISSUE THREAD

**Issue by atSeptine** [EricAndrechek/homebridge-display#123]
Hello, in homebridge v1.3.0 the Accessory Control buttons not showing on display.!!

**Comment by EricAndrechek** [comment]
Were they showing on the previous version for you? Also make sure Homebridge is running in insecure mode in order for this to work.

**Comment by atSeptine** [comment]
Hello, my homebridge always run on insecure mode.! In homebridge v1.1.7 and v1.2.5 the Buttons showing on Display. In v1.3.0 - 1.3....Beta the Buttons not showing.

**Comment by EricAndrechek** [comment]
Ok, can you try giving your device that is used to show the display (ie your iPad) a hard refresh of the website. In the last version I updated the web sockets to a new version that is incompatible with the older version. If your device has a cached version of the old web socket library it will not work. If it is a computer, try pressing control-R (or command-R on Mac). On an iOS device, like an iPad, you will need to go to Settings>Safari>Clear History and Web Data

Let me know if that solves it for you. The other thing you can try is to open it up on your computer if you haven't already and see if that works.

**Comment by atSeptine** [comment]
Ok, very thanks vor the Instructions and Service, I have all this do but the button are not on screen.
Now i go back to homebridge v1.2.5 then works the plugin and i see Buttons in on a website.
Maybe a bug in homebridge...??

**Comment by EricAndrechek** [comment]
Ok, I was able to reproduce the bug on my side. I will investigate further and see if I can get a fix figured out.

**Comment by atSeptine** [comment]
Ok, thank you for the top service.!!!

**Comment by EricAndrechek** [comment]
Ok, I have identified and fixed the issue! Updating to the latest release should fix your issue, let me know if it doesn't!
