### ISSUE TITLE
Spotify not displaying

### ISSUE THREAD

**Issue by Jacksonbm1** [EricAndrechek/homebridge-display#149]
**Describe the bug**
Not getting spotify to work

**To Reproduce**
Config fields:
- Homebridge-Display Port *: 6969
- fourth box: Spotify Control
- various boxes
- spotify: client ID & client secret are correctly entered
- callbackurl: pretty sure this is where I'm erroring. I have: `http://<pi-ip>:6969/callback` and I tried to put that in spotify under "White-listed addresses to redirect to after authentication success OR failure (e.g. http://mysite.com/callback/)"

**Expected behavior**
Should be getting spotify control, but getting none.

**Homebridge Server (please complete the following information):**
 - OS: Raspbian GNU/Linux Buster (10)

 - NodeJS Version v14.16.0
 - Homebride-Display Version: homebridge-display v2.1.2

**Display Client (please complete the following information):**
 - Device: macbook pro (eventually kindle fire running fully kiosk browser
 - OS: 11.2.3
 - Browser chrome

**Screenshots**

**Logs**
You have not yet given homebridge-display access to your Spotify account. To do so go to: https://accounts.spotify.com/authorize?response_type=code&client_id=<MY CLINET ID>&scope=user-read-private%20user-read-playback-state%20user-modify-playback-state%20user-library-modify%20user-library-read&redirect_uri=http%3A%2F%2F192.168.86.43%3A6969%2Fcallback
then restart the server.

URL does nothing

**Additional context**

**Comment by Jacksonbm1** [comment]
Ooop, wow literally just tested the URL again and it works. I think I first had tried the URL (failed), then added the callback URL to spotify correctly --> failed (Because I never authorized). So, I thought the URL was still broken. Clicking the URL again worked --> it's working now! This is a really awesome thing you've got going on here btw!

**Comment by EricAndrechek** [comment]
Haha glad to hear you got it working!
