### ISSUE TITLE
Request: A light version that displays on a RaspberryPi with attached display 

### ISSUE THREAD

**Issue by jkuss** [EricAndrechek/homebridge-display#2]
I have an Adafruit TFT display attached directly to my Raspberry Pi that runs  home bridge. I would love to have a widget or 2 running on it locally for when I glance at it.

**Comment by EricAndrechek** [comment]
After looking into it, I am going to mark this issue as wontfix, as I would prefer to keep things simple and leave it all as frontend website code. You'll need to get the website running on the display somehow to make this work, but even then, this plugin currently can only display exactly 6 widgets, so it will look a little bit strange.
